In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv('https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/fa71405126017e6a37bea592440b4bee94bf7b9e/titanic.csv')

In [3]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
data.shape

(891, 12)

In [5]:
data.describe(include='all').T

count unique                                         top freq  \
PassengerId   891    NaN                                         NaN  NaN   
Survived      891    NaN                                         NaN  NaN   
Pclass        891    NaN                                         NaN  NaN   
Name          891    891  Penasco y Castellana, Mr. Victor de Satode    1   
Sex           891      2                                        male  577   
Age           714    NaN                                         NaN  NaN   
SibSp         891    NaN                                         NaN  NaN   
Parch         891    NaN                                         NaN  NaN   
Ticket        891    681                                      347082    7   
Fare          891    NaN                                         NaN  NaN   
Cabin         204    147                                 C23 C25 C27    4   
Embarked      889      3                                           S  644   

                 mean       std   min     25%      50%    75%      max  
PassengerId       446   257.354     1   223.5      446  668.5      891  
Survived     0.383838  0.486592     0       0        0      1        1  
Pclass        2.30864  0.836071     1       2        3      3        3  
Name              NaN       NaN   NaN     NaN      NaN    NaN      NaN  
Sex               NaN       NaN   NaN     NaN      NaN    NaN      NaN  
Age           29.6991   14.5265  0.42  20.125       28     38       80  
SibSp        0.523008   1.10274     0       0        0      1        8  
Parch        0.381594  0.806057     0       0        0      0        6  
Ticket            NaN       NaN   NaN     NaN      NaN    NaN      NaN  
Fare          32.2042   49.6934     0  7.9104  14.4542     31  512.329  
Cabin             NaN       NaN   NaN     NaN      NaN    NaN      NaN  
Embarked          NaN       NaN   NaN     NaN      NaN    NaN      NaN

In [6]:
data.columns.unique()

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [7]:
data.columns.isna().sum()

0

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [9]:
categorical=[var for var in data.columns if data[var].dtype =='O']
categorical

['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']

In [10]:
numerical=[var for var in data.columns if data[var].dtype !='O']
numerical

['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

In [11]:
data[categorical]
category=['Sex', 'Embarked']

In [12]:
category

['Sex', 'Embarked']

In [13]:
data[category].isnull().sum()

Sex         0
Embarked    2
dtype: int64

In [14]:
data[numerical].head()

PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0            1         0       3  22.0      1      0   7.2500
1            2         1       1  38.0      1      0  71.2833
2            3         1       3  26.0      0      0   7.9250
3            4         1       1  35.0      1      0  53.1000
4            5         0       3  35.0      0      0   8.0500

In [15]:
data['Parch'].unique()

array([0, 1, 2, 5, 3, 4, 6], dtype=int64)

In [16]:
data['Pclass'].unique()

array([3, 1, 2], dtype=int64)

In [17]:
data['SibSp'].unique()

array([1, 0, 3, 4, 2, 5, 8], dtype=int64)

In [18]:
data[numerical].isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Age            177
SibSp            0
Parch            0
Fare             0
dtype: int64

In [19]:
target=data['Survived']

In [20]:
numeric=['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']
data[numeric].head()

Pclass   Age  SibSp  Parch     Fare
0       3  22.0      1      0   7.2500
1       1  38.0      1      0  71.2833
2       3  26.0      0      0   7.9250
3       1  35.0      1      0  53.1000
4       3  35.0      0      0   8.0500

In [21]:
data['Age'].unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [22]:
data['Age'].fillna(data['Age'].mode()[0], inplace=True)

In [23]:
data.Age.isnull().sum()

0

In [24]:
data['Age'].unique()

array([22.  , 38.  , 26.  , 35.  , 24.  , 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 46.  , 59.  , 71.  ,
       37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 , 51.  ,
       55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  , 45.5 ,
       20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  , 60.  ,
       10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  , 70.  ,
       24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [25]:
data[numeric]

Pclass   Age  SibSp  Parch     Fare
0         3  22.0      1      0   7.2500
1         1  38.0      1      0  71.2833
2         3  26.0      0      0   7.9250
3         1  35.0      1      0  53.1000
4         3  35.0      0      0   8.0500
..      ...   ...    ...    ...      ...
886       2  27.0      0      0  13.0000
887       1  19.0      0      0  30.0000
888       3  24.0      1      2  23.4500
889       1  26.0      0      0  30.0000
890       3  32.0      0      0   7.7500

[891 rows x 5 columns]

In [26]:
data[category]

Sex Embarked
0      male        S
1    female        C
2    female        S
3    female        S
4      male        S
..      ...      ...
886    male        S
887  female        S
888  female        S
889    male        C
890    male        Q

[891 rows x 2 columns]

In [27]:
df=data[category+numeric]
df

Sex Embarked  Pclass   Age  SibSp  Parch     Fare
0      male        S       3  22.0      1      0   7.2500
1    female        C       1  38.0      1      0  71.2833
2    female        S       3  26.0      0      0   7.9250
3    female        S       1  35.0      1      0  53.1000
4      male        S       3  35.0      0      0   8.0500
..      ...      ...     ...   ...    ...    ...      ...
886    male        S       2  27.0      0      0  13.0000
887  female        S       1  19.0      0      0  30.0000
888  female        S       3  24.0      1      2  23.4500
889    male        C       1  26.0      0      0  30.0000
890    male        Q       3  32.0      0      0   7.7500

[891 rows x 7 columns]

In [28]:
df.isnull().sum()

Sex         0
Embarked    2
Pclass      0
Age         0
SibSp       0
Parch       0
Fare        0
dtype: int64

In [29]:
df['Embarked'].fillna(df['Embarked'].mode()[0],inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:6245: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)


In [30]:
df.isnull().sum()

Sex         0
Embarked    0
Pclass      0
Age         0
SibSp       0
Parch       0
Fare        0
dtype: int64

In [31]:
assert pd.notnull(df).all().all()

In [32]:
X=df.iloc[:,:]
y=target

In [33]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y=train_test_split(X,y,test_size=0.3,random_state=0)

In [34]:
import category_encoders as ce
encoder=ce.OrdinalEncoder(cols=category)
train_x=encoder.fit_transform(train_x)
test_x=encoder.transform(test_x)

In [35]:
train_x,test_x

(     Sex  Embarked  Pclass   Age  SibSp  Parch     Fare
 857    1         1       1  51.0      0      0  26.5500
 52     2         2       1  49.0      1      0  76.7292
 386    1         1       3   1.0      5      2  46.9000
 124    1         1       1  54.0      0      1  77.2875
 578    2         2       3  24.0      1      0  14.4583
 ..   ...       ...     ...   ...    ...    ...      ...
 835    2         2       1  39.0      1      1  83.1583
 192    2         1       3  19.0      1      0   7.8542
 629    1         3       3  24.0      0      0   7.7333
 559    2         1       3  36.0      1      0  17.4000
 684    1         1       2  60.0      1      1  39.0000
 
 [623 rows x 7 columns],
      Sex  Embarked  Pclass   Age  SibSp  Parch      Fare
 495    1         2       3  24.0      0      0   14.4583
 648    1         1       3  24.0      0      0    7.5500
 278    1         3       3   7.0      4      1   29.1250
 31     2         2       1  24.0      1      0  146.5208

In [36]:
from sklearn.preprocessing import RobustScaler
scaler=RobustScaler()
train_x=scaler.fit_transform(train_x)
test_x=scaler.transform(test_x)

In [37]:
train_x=pd.DataFrame(train_x,columns=X.columns)
test_x=pd.DataFrame(test_x,columns=X.columns)

In [38]:
train_x

Sex  Embarked    Pclass       Age  SibSp  Parch      Fare
0    0.0       0.0 -1.333333  2.000000    0.0    0.0  0.492275
1    1.0       1.0 -1.333333  1.846154    1.0    0.0  2.630973
2    0.0       0.0  0.000000 -1.846154    5.0    2.0  1.359616
3    0.0       0.0 -1.333333  2.230769    0.0    1.0  2.654768
4    1.0       1.0  0.000000 -0.076923    1.0    0.0 -0.023088
..   ...       ...       ...       ...    ...    ...       ...
618  1.0       1.0 -1.333333  1.076923    1.0    1.0  2.904989
619  1.0       0.0  0.000000 -0.461538    1.0    0.0 -0.304563
620  0.0       2.0  0.000000 -0.076923    0.0    0.0 -0.309716
621  1.0       0.0  0.000000  0.846154    1.0    0.0  0.102291
622  0.0       0.0 -0.666667  2.692308    1.0    1.0  1.022909

[623 rows x 7 columns]

In [39]:
test_x

Sex  Embarked    Pclass       Age  SibSp  Parch      Fare
0    0.0       1.0  0.000000 -0.076923    0.0    0.0 -0.023088
1    0.0       0.0  0.000000 -0.076923    0.0    0.0 -0.317528
2    0.0       2.0  0.000000 -1.384615    4.0    1.0  0.602025
3    1.0       1.0 -1.333333 -0.076923    1.0    0.0  5.605575
4    1.0       1.0  0.000000  0.307692    0.0    2.0  0.010476
..   ...       ...       ...       ...    ...    ...       ...
263  0.0       0.0 -1.333333  1.153846    0.0    0.0 -0.639318
264  0.0       2.0  0.000000 -0.076923    0.0    0.0  0.021311
265  0.0       1.0  0.000000  0.153846    1.0    0.0 -0.023263
266  1.0       0.0  0.000000 -0.538462    0.0    0.0 -0.319838
267  0.0       1.0 -1.333333 -0.076923    0.0    0.0  0.542176

[268 rows x 7 columns]

In [41]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(random_state=0)
rfc=rfc.fit(train_x,train_y)
y_pred=rfc.predict(test_x)

In [42]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [43]:
print('Default Accuracy Of RFC : ',accuracy_score(test_y,y_pred))

Default Accuracy Of RFC :  0.8134328358208955


In [44]:
confusion_matrix(test_y,y_pred)

array([[145,  23],
       [ 27,  73]], dtype=int64)

In [45]:
print(classification_report(test_y,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.86      0.85       168
           1       0.76      0.73      0.74       100

    accuracy                           0.81       268
   macro avg       0.80      0.80      0.80       268
weighted avg       0.81      0.81      0.81       268



## Performing Cross Validation Hyperparameter Tuning

In [46]:
from sklearn.model_selection import GridSearchCV

In [47]:
params={
    'n_estimators':(10,20,40,80,100),
    'criterion':('gini','entropy'),
    'max_depth':(3,5,7,9,10),
    'max_features':('auto','sqrt'),
    'min_samples_split':(2,4,6)
}

In [48]:
RF_gridcv=GridSearchCV(RandomForestClassifier(),param_grid=params,cv=3)

In [49]:
RF_CV_model=RF_gridcv.fit(train_x,train_y)

In [50]:
RF_CV_model.best_estimator_

RandomForestClassifier(max_depth=5, max_features='sqrt', min_samples_split=6,
                       n_estimators=20)

In [51]:
best_model=RandomForestClassifier(criterion='entropy', max_depth=5, n_estimators=20)
best_model.fit(train_x,train_y)
y_pred_best=best_model.predict(test_x)
y_pred_best_train=best_model.predict(train_x)

In [52]:
print('Best Parameter Accuracy Of RFC : ',accuracy_score(test_y,y_pred))
print('Best Param Train Accuracy Of RFC : ',accuracy_score(train_y,y_pred_best_train))

Best Parameter Accuracy Of RFC :  0.8134328358208955
Best Param Train Accuracy Of RFC :  0.8539325842696629


In [53]:
confusion_matrix(test_y,y_pred_best)

array([[151,  17],
       [ 34,  66]], dtype=int64)

In [54]:
print(classification_report(test_y,y_pred_best))

              precision    recall  f1-score   support

           0       0.82      0.90      0.86       168
           1       0.80      0.66      0.72       100

    accuracy                           0.81       268
   macro avg       0.81      0.78      0.79       268
weighted avg       0.81      0.81      0.81       268



In [55]:
confusion_matrix(train_y,y_pred_best_train)

array([[364,  17],
       [ 74, 168]], dtype=int64)