## Chi-Square Test-
The test is applied when you have two categorical variables from a single population. It is used to determine whether there is a significant association between the two variables.

In [1]:
import pandas as pd
import scipy.stats as stats
import seaborn as sns
import numpy as np

In [2]:
df=sns.load_dataset('tips')
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [3]:
observe_value=pd.crosstab(df['sex'],df['smoker'])
observe_value

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [4]:
observe_value=observe_value.values
observe_value

array([[60, 97],
       [33, 54]], dtype=int64)

In [12]:
from scipy.stats import chi2_contingency
value=chi2_contingency(observe_value)
value

(0.008763290531773594,
 0.925417020494423,
 1,
 array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [13]:
expect_value=value[3]
expect_value

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [14]:
col=len(df.iloc[:2,0])
row=len(df.iloc[0,:2])
# Finding Digree Of Oreder=(column-1)*(rows-1)
ddof=(col-1)*(row-1)
print('Digree Of Oreder : ',ddof)

Digree Of Oreder :  1


In [15]:
# Value Of Alpha =0.05 . it's Significant Level Value
alpha=0.05
print('Alpha Is : ',alpha)

Alpha Is :  0.05


In [17]:
chi_square=sum([(o-e)**2/e for o,e in zip(observe_value,expect_value)])
chi_square

array([0.00119737, 0.00073745])

In [18]:
chi_square=sum([(o-e)**2/e for o,e in zip(observe_value,expect_value)])
chi_square

array([0.00119737, 0.00073745])

In [19]:
chi_square_statastic=chi_square[0]+chi_square[1]
chi_square_statastic

0.001934818536627623

In [21]:
print("chi-square statistic:",chi_square_statastic)

chi-square statistic: 0.001934818536627623


In [23]:
from scipy.stats import chi2
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('Critical Value : ',critical_value)

Critical Value :  3.841458820694124


In [24]:
p_value=1-chi2.cdf(x=chi_square_statastic,df=ddof)
print('P-Value is : ',p_value)

P-Value is :  0.964915107315732


In [25]:
print("chi-square statistic:",chi_square_statastic)
print('Critical Value      : ',critical_value)
print('P-Value is          : ',p_value)
print('Alpha Is            : ',alpha)
print('Digree Of Oreder    : ',ddof)

chi-square statistic: 0.001934818536627623
Critical Value      :  3.841458820694124
P-Value is          :  0.964915107315732
Alpha Is            :  0.05
Digree Of Oreder    :  1


In [27]:
if chi_square_statastic >= critical_value:
    print('Reject H0 ,There is Relatioship Between Two Variables')
else:
    print('Accept H0 ,There is No Relatioship Between Two Variables')
    
if p_value <= alpha:
      print('Reject H0 ,There is Relatioship Between Two Variables')
else:
    print('Accept H0 ,There is No Relatioship Between Two Variables')

Accept H0 ,There is No Relatioship Between Two Variables
Accept H0 ,There is No Relatioship Between Two Variables


## Anova Test(F-Test)
The t-test works well when dealing with two groups, but sometimes we want to compare more than two groups at the same time.

For example, if we wanted to test whether petal_width age differs based on some categorical variable like species, we have to compare the means of each level or group the variable

## One Way F-test(Anova) :-

It tell whether two or more groups are similar or not based on their mean similarity and f-score.

Example : there are 3 different category of iris flowers and their petal width and need to check whether all 3 group are similar or not

In [28]:
import pandas as pd
import seaborn as sns
import scipy.stats as stats

In [29]:
df=sns.load_dataset('iris')
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [30]:
df_anova=df[['petal_width','species']]
df_anova

petal_width    species
0            0.2     setosa
1            0.2     setosa
2            0.2     setosa
3            0.2     setosa
4            0.2     setosa
..           ...        ...
145          2.3  virginica
146          1.9  virginica
147          2.0  virginica
148          2.3  virginica
149          1.8  virginica

[150 rows x 2 columns]

In [34]:
groups=pd.unique(df_anova.species.values)
groups

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [35]:
d_data={group:df_anova['petal_width'][df_anova.species==group] for group in groups}

In [36]:
d_data

{'setosa': 0     0.2
 1     0.2
 2     0.2
 3     0.2
 4     0.2
 5     0.4
 6     0.3
 7     0.2
 8     0.2
 9     0.1
 10    0.2
 11    0.2
 12    0.1
 13    0.1
 14    0.2
 15    0.4
 16    0.4
 17    0.3
 18    0.3
 19    0.3
 20    0.2
 21    0.4
 22    0.2
 23    0.5
 24    0.2
 25    0.2
 26    0.4
 27    0.2
 28    0.2
 29    0.2
 30    0.2
 31    0.4
 32    0.1
 33    0.2
 34    0.2
 35    0.2
 36    0.2
 37    0.1
 38    0.2
 39    0.2
 40    0.3
 41    0.3
 42    0.2
 43    0.6
 44    0.4
 45    0.3
 46    0.2
 47    0.2
 48    0.2
 49    0.2
 Name: petal_width, dtype: float64,
 'versicolor': 50    1.4
 51    1.5
 52    1.5
 53    1.3
 54    1.5
 55    1.3
 56    1.6
 57    1.0
 58    1.3
 59    1.4
 60    1.0
 61    1.5
 62    1.0
 63    1.4
 64    1.3
 65    1.4
 66    1.5
 67    1.0
 68    1.5
 69    1.1
 70    1.8
 71    1.3
 72    1.5
 73    1.2
 74    1.3
 75    1.4
 76    1.4
 77    1.7
 78    1.5
 79    1.0
 80    1.1
 81    1.0
 82    1.2
 83    1.6
 84    1.5
 85  

In [37]:
F,p=stats.f_oneway(d_data['setosa'],d_data['versicolor'],d_data['virginica'])
p

4.169445839443116e-85

In [38]:
if p < 0.05:
    print('Reject H0 ,There is Relatioship Between Two Variables')
else:
    print('Accept H0 ,There is No Relatioship Between Two Variables')

Reject H0 ,There is Relatioship Between Two Variables
